### ISSUE TITLE
Error in max_mismatches argument

### ISSUE THREAD

**Issue by Jigyasa3** [ZoyavanMeel/ORCA#7]
hi @Mister-Teapot  and @ZoyavanMeel ,

I am able to run ORCA with argument ORCA.from_accession() but I am unable to change the default max_mismatches argument
Any suggestions?

#code-
`>>>orca=ORCA.from_accession("NC_001621",email=email)`
`>>>orca.find_oriCs(show_info=True)`
`>>>orca.find_oriCs(show_info=True,max_mismatches=2)`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ORCA.find_oriCs() got an unexpected keyword argument 'max_mismatches'

**Comment by ZoyavanMeel** [comment]
Hi @Jigyasa3,
Sorry for the confusion, but any keyword arguments should be specified in the constructor (`from_accession`), not when calling the `find_oriCs` function. Hope that helps. I will try to clear this up in the readme/documentation!

**Comment by Jigyasa3** [comment]
Hi @ZoyavanMeel ,

Thank you for replying!
I was able to get a list of all DnaA boxes with two mismatches using this script-
`ORCA.get_dnaa_boxes_with_mismatches(box_list=['TTATACACA', 'TTATTCACA', 'TTATCCACA', 'TTATGCACA'], max_mismatches=2)`
How do I add this info to `find_oriC()`  function?

**Comment by ZoyavanMeel** [comment]
I see you're using the consensus _DnaA_-box sequence: `TTAT(A|T|C|G)CACA`. These three methods would be equivalent

```python
# list representation of `TTAT(A|T|C|G)CACA`
boxes = ['TTATACACA', 'TTATTCACA', 'TTATCCACA', 'TTATGCACA']

# 1. use the parameters in the constructor
orca = ORCA.from_accession("NC_000919", email="email", dnaa_boxes=boxes, max_mismatches=2)
orca.find_oriCs(show_info=True)

# 2. first generate boxes with mismatches, then allow for 0 further mismatches
boxes_with_mismatches = ORCA.get_dnaa_boxes_with_mismatches(box_list=boxes, max_mismatches=2)
orca = ORCA.from_accession("NC_000919", email="email", dnaa_boxes=boxes_with_mismatches, max_mismatches=0)
orca.find_oriCs(show_info=True)

# 3. only changing the max_mismatches parameter
orca = ORCA.from_accession("NC_000919", email="email", max_mismatches=2)
orca.find_oriCs(show_info=True)
```

Saving the boxes with all allowed mismatches and loading them into ORCA with zero further allowed mismatches can be a way to save on computation time, especially when using `max_mismatches` > 2, since generating all strings that fit these requirements can become quite expensive.

Edit: I made a mistake previously, ORCA uses `max_mismatches = 0` as default
