### ISSUE TITLE
Print output to variable or a output file

### ISSUE THREAD

**Issue by Jigyasa3** [ZoyavanMeel/ORCA#8]
Hi @Mister-Teapot  and @ZoyavanMeel 

Sorry for asking so many questions!

I would like to print the `orca.find_oriCs()` output to a variable or (ideally) an output file.

I have tried different versions of `orca.find_oriCs()` with `show_info=False` or `show_info=True` but its still not working, any suggestions?

**Comment by ZoyavanMeel** [comment]
Hi @Jigyasa3,

No worries! It's good to see what is clear and what isn't :)
There is no way to save the results to a file directly at the moment, but I wrote this little function with pandas that might help you:
```python
from orcapy import ORCA
import pandas as pd

def save_output(orca: ORCA, path: str) -> None:
    """
    `orca` is a fitted ORCA-object (find_oriCS has been called).
    `path` is a path to the file you want to save the results in
    """
    with open(path, "w") as fh:
        attrs = ['predictions', 'Z_scores', 'G_scores', 'D_scores', 'oriC_middles']
        orca_results_dict = {attr: getattr(orca, attr) for attr in attrs}
        pd.DataFrame(orca_results_dict).to_csv(path)

orca = ORCA.from_accession("NC_014248", email="email@address.com", max_mismatches=1)
orca.find_oriCs()
save_output(orca, "results.csv")
```

**Comment by ZoyavanMeel** [comment]
The results that are printed with `show_info` enabled simply a prettyprint of the values stored in the `predictions`, `Z_scores`, `G_scores`, `D_scores` and `oriC_middles` attributes of the fitted `ORCA`-object. Hope that helps :)

**Comment by Jigyasa3** [comment]
thank you so much!
